(function(g){var window=this;var F4=function(a,b,c){var d=b.ua();g.I(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Ac(c?c:"mqdefault.jpg");var f=b instanceof g.CB&&b.lengthSeconds?g.sR(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.zE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.CB?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.kj||g.YN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.ci(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.BE&&(d.playlist_length=b.getLength());a.update(d)},G4=function(a,b){g.xD.call(this,{C:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},H4=function(a){g.V.call(this,{C:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{C:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-upnext-top",J:[{C:"span",G:"ytp-upnext-header",V:"Up Next"},{C:"span",G:"ytp-upnext-title",V:"{{title}}"},{C:"span",G:"ytp-upnext-author",V:"{{author}}"}]},{C:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{C:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{C:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",G:"ytp-upnext-bottom",J:[{C:"span",G:"ytp-upnext-cancel"},{C:"span",G:"ytp-upnext-paused",V:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.V({C:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},V:"Cancel"});g.B(this,this.A);this.A.da("click",this.NI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.B=this.o=this.u=null;this.F=new g.J(this.dm,5E3,this);g.B(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.AK);this.Uy();this.K(a,"autonavvisibility",this.Uy);this.K(a,"mdxnowautoplaying",
this.TJ);this.K(a,"mdxautoplaycanceled",this.UJ);this.K(a,"mdxautoplayupnext",this.qB);3==this.l.getPresentingPlayerType()&&(a=(a=g.OK(g.IK(this.l)))?a.FD():null)&&this.qB(a)},I4=function(a,b){if(!a.o){g.rq("a11y-announce","Up Next "+a.u.title);
a.H=g.M();a.o=new g.J((0,g.x)(a.mp,a,b),25);a.mp(b);var c=b||g.P(g.W(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.ro(a.element,"ytp-upnext-autoplay-paused")},K4=function(a){J4(a);
a.H=g.M();a.mp();g.H(a.element,"ytp-upnext-autoplay-paused")},J4=function(a){a.o&&(a.o.dispose(),a.o=null)},L4=function(a,b){b=void 0===b?!1:b;
if(g.O(g.W(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.ua(),a.dm(),a.B=new Notification("Up Next",{body:c.title,icon:c.Ac()}),a.D=a.K(a.B,"click",a.sK),a.F.start())}J4(a);a.l.nextVideo(!1,b)},M4=function(a){G4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.V({C:"div",G:"ytp-subscribe-card",J:[{C:"img",G:"ytp-author-image",L:{src:b.Wd}},{C:"div",G:"ytp-subscribe-card-right",J:[{C:"div",G:"ytp-author-name",V:b.author},{C:"div",G:"html5-subscribe-button-container"}]}]});g.B(this,this.l);this.l.g(this.element);this.o=new g.FW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Uf,b.subscribed,"trailer-endscreen",null,null,a);g.B(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},N4=function(a){var b=
g.W(a),c=g.tx||g.Bh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.V.call(this,{C:"a",W:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{C:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-videowall-still-info",J:[{C:"span",G:"ytp-videowall-still-info-bg",J:[{C:"span",G:"ytp-videowall-still-info-content",L:c,J:[{C:"span",G:"ytp-videowall-still-info-title",V:"{{title}}"},{C:"span",G:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{C:"span",G:"ytp-videowall-still-info-live",V:"Live"},{C:"span",G:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{C:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{C:"span",V:"{{playlist_length}}"},")"]}]},{C:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{C:"span",G:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Xs(this);g.B(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.B);g.W(a).D&&g.MO(a.app.T,this.element,this);this.B()},O4=function(a){g.dL(a.l,a.element);
var b=a.o.ua().videoId,c=a.o.getPlaylistId();g.MY(a.l.app,b,a.o.Cb,c,void 0,void 0)},P4=function(a){G4.call(this,a,"videowall-endscreen");
this.B=a;this.A=0;this.o=[];this.D=this.O=this.u=null;this.F=this.P=!1;this.M=null;this.ca=new g.Xs(this);g.B(this,this.ca);this.H=new g.J(g.Qa(g.H,this.element,"ytp-show-tiles"),0);g.B(this,this.H);var b=new g.V({C:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.aQ()]});g.B(this,b);b.g(this.element);b.da("click",this.eG,this);this.I=new g.rD({C:"div",G:"ytp-endscreen-content"});g.B(this,this.I);this.I.g(this.element);b=new g.V({C:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.bQ()]});g.B(this,b);b.g(this.element);b.da("click",this.dG,this);this.l=new H4(a);g.B(this,this.l);g.aL(this.player,this.l.element,4);this.hide()},Q4=function(a){return g.bL(a.player)&&a.Ku()&&!a.D},R4=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.HS(g.W(a.B),c);
g.B(a,c);return c})},S4=function(a){var b=a.Te();
b!=a.P&&(a.P=b,a.player.N("autonavvisibility"))},U4=function(a){g.qL.call(this,a);
this.g=null;this.i=new g.Xs(this);g.B(this,this.i);this.l=g.W(a);T4(a)?this.g=new P4(this.player):this.l.Ja?this.g=new M4(this.player):this.g=new G4(this.player);g.B(this,this.g);g.aL(this.player,this.g.element,4);this.nA();this.i.K(a,"videodatachange",this.nA,this);this.i.K(a,g.yE("endscreen"),this.sF,this);this.i.K(a,"crx_endscreen",this.tF,this)},T4=function(a){a=g.W(a);
return a.Ea&&!a.Ja};
g.t(G4,g.xD);G4.prototype.create=function(){this.created=!0};
G4.prototype.destroy=function(){this.created=!1};
G4.prototype.Ku=function(){return!1};
G4.prototype.Te=function(){return!1};g.t(H4,g.V);g.h=H4.prototype;g.h.dm=function(){this.B&&(this.F.stop(),this.Na(this.D),this.D=null,this.B.close(),this.B=null)};
g.h.Uy=function(){g.wD(this,this.l.Te())};
g.h.sK=function(){window.focus();this.dm()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.mp=function(a){a=a||g.P(g.W(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.M()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?L4(this,!0):this.o&&this.o.start()};
g.h.AK=function(a){!g.$d(this.A.element,g.ps(a))&&g.KS(a,this.l)&&L4(this)};
g.h.NI=function(){g.KK(this.l,!0)};
g.h.TJ=function(a){this.l.getPresentingPlayerType();this.show();I4(this,a)};
g.h.qB=function(a){this.l.getPresentingPlayerType();this.u&&this.u.ua().videoId==a.ua().videoId||(this.u=a,F4(this,a,"hqdefault.jpg"))};
g.h.UJ=function(){this.l.getPresentingPlayerType();J4(this);this.hide()};
g.h.U=function(){J4(this);this.dm();g.V.prototype.U.call(this)};g.t(M4,G4);g.t(N4,g.V);N4.prototype.D=function(a){g.KS(a,this.l,this.A,this.o.Cb||void 0)&&O4(this)};
N4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.vs(a)||(O4(this),g.us(a))}};
N4.prototype.B=function(){var a=this.l.getVideoData(),b=g.W(this.l);this.A=a.Cc?!1:b.i};g.t(P4,G4);g.h=P4.prototype;g.h.create=function(){G4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=R4(this,a),this.O=a);this.Mf();this.ca.K(this.player,"appresize",this.Mf);this.ca.K(this.player,"onVideoAreaChange",this.Mf);this.ca.K(this.player,"videodatachange",this.fG);this.ca.K(this.player,"autonavchange",this.zr);this.ca.K(this.player,"autonavcancel",this.cG);a=this.O.autonavState;a!=this.M&&this.zr(a);this.ca.K(this.element,"transitionend",this.QL)};
g.h.destroy=function(){g.Zs(this.ca);g.qf(this.o);this.o=[];this.u=null;G4.prototype.destroy.call(this);g.ro(this.element,"ytp-show-tiles");this.H.stop();this.M=this.O.autonavState};
g.h.Ku=function(){return 1!=this.O.autonavState};
g.h.show=function(){G4.prototype.show.call(this);g.ro(this.element,"ytp-show-tiles");g.W(this.player).g?g.Fo(this.H):this.H.start();(this.F||this.D&&this.D!=this.O.clientPlaybackNonce)&&g.KK(this.player,!1);Q4(this)?(S4(this),2==this.O.autonavState?g.O(g.W(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?L4(this.l,!0):I4(this.l):3==this.O.autonavState&&K4(this.l)):(g.KK(this.player,!0),S4(this))};
g.h.hide=function(){G4.prototype.hide.call(this);K4(this.l);S4(this)};
g.h.QL=function(a){g.ps(a)==this.element&&this.Mf()};
g.h.Mf=function(){if(this.u&&this.u.length){g.H(this.element,"ytp-endscreen-paginate");var a=g.SK(this.B,!0,this.B.isFullscreen()),b=g.ND(this.B);b&&(b=b.dc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,v=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(v)n-=r*m,b+=2;else if(z)n-=
p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.nd(a.width/m||1,1,1.21);n*=g.nd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.Qh(a,m,n);g.yh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;F4(c,f,"hqdefault.jpg");g.I(this.element,"ytp-endscreen-takeover",Q4(this));S4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=
c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.od(p+this.A,l),0!=r){v=this.o[c];v||(v=new N4(this.player),this.o[c]=v,a.appendChild(v.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),F=Math.floor(n*(k+r)/e)-z-4,E=Math.floor(m*(f+r)/b)-C-4;g.Gh(v.element,C,z);g.Qh(v.element,E,F);g.yh(v.element,"transitionDelay",(k+f)/20+"s");g.I(v.element,"ytp-videowall-still-mini",1==r);g.I(v.element,"ytp-videowall-still-large",2<r);r=v;p=this.u[p];r.o!=p&&(r.o=p,F4(r,p,g.po(r.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Cb)&&p.itct)&&(v=r.l,g.W(v).D&&g.NO(v.app.T,r.element,p));c++}g.I(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.pf(e);this.o.length=c}};
g.h.fG=function(){var a=this.player.getVideoData();this.O!=a&&(this.A=0,this.u=R4(this,a),this.O=a,this.Mf())};
g.h.dG=function(){this.A+=this.o.length;this.Mf()};
g.h.eG=function(){this.A-=this.o.length;this.Mf()};
g.h.HE=function(){return!!this.l.o};
g.h.zr=function(a){1==a?(this.F=!1,this.D=this.O.clientPlaybackNonce,J4(this.l),this.Fa()&&this.Mf()):(this.F=!0,this.Fa()&&Q4(this)&&(2==a?I4(this.l):3==a&&K4(this.l)))};
g.h.cG=function(a){if(a){for(a=0;a<this.o.length;a++)g.eL(this.B,this.o[a].element,!0);this.zr(1)}else this.D=null,this.F=!1;this.Mf()};
g.h.Te=function(){return this.Fa()&&Q4(this)};g.t(U4,g.qL);g.h=U4.prototype;g.h.Tk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!T4(this.player)||b;a=a.Rc||g.lz(a.Oa);var c=g.lY(this.player.app);return b&&!a&&!c};
g.h.Te=function(){return this.g.Te()};
g.h.CE=function(){return this.Te()?this.g.HE():!1};
g.h.U=function(){g.XK(this.player,"endscreen");g.qL.prototype.U.call(this)};
g.h.load=function(){g.qL.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.qL.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.sF=function(a){this.Tk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.tF=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.nA=function(){g.XK(this.player,"endscreen");var a=this.player.getVideoData();a=new g.vE(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.B(this,a);var b=new g.vE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.B(this,b);g.UK(this.player,[a,b])};g.MV.endscreen=U4;})(_yt_player);
